services:
  UFC-MA_db:
    image: postgres:15
    container_name: UFC-MA_db
    environment:
      - POSTGRES_DB=UFC-MA_db
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=123456
    volumes:
      - UFC-MA_db_data:/var/lib/postgresql/data
    networks:
      - odoo_net_UFC-MA  # Added a space after the hyphen

  UFC-MA_app:
    image: odoo:18
    container_name: UFC-MA_app
    depends_on:
      - UFC-MA_db
    environment:
      - HOST=UFC-MA_db
      - USER=odoo
      - PASSWORD=123456
    ports:
      - "8469:8069"
    volumes:
      - UFC-MA_odoo_data:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
    networks:
      - odoo_net_UFC-MA

networks:
  odoo_net_UFC-MA:
    name: odoo_net_UFC-MA
    driver: bridge

volumes:
  UFC-MA_db_data:
    name: UFC-MA_db_data
  UFC-MA_odoo_data:
    name: UFC-MA_odoo_data