map $client $valid_client {
    default 0;  # Everything is valid
    "ufc" 1;
}

server {
    listen 80;
        server_name ~^(?<client>ufc)\.experts-itn\.com$;  # The client is the instance name


    access_log /var/log/nginx/custom-access-logs.log custom_log;

    if ($valid_client = 0) {
        return 404;
    }

    location / {
        resolver 127.0.0.11 valid=30s;  # DNS provided by Docker

        set $upstream "${client}_app";
        proxy_pass http://$upstream:8069;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_redirect off;
    }
}